service: orders-source

configValidationMode: error

provider:
  name: aws
  logRetentionInDays: 7
  region: us-east-1
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: com.reference-architecture.deploys
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  environment:
    TABLE_NAME: ${self:custom.tableName}
  tags:
    lumigo:auto-trace: 'true'

custom:
  esbuild:
    minify: true
  prune:
    automatic: true
    number: 1
  tableName: ${self:service}

appSync:
  name: orders-source-api
  schema: orders/schema.api.graphql
  authentication:
    type: API_KEY
  apiKeys: 
  - name: orders-api-key
    description: The API key for Orders
    expiresAfter: 300d
  logging:
    level: ALL
    retentionInDays: 7
  resolvers:
    Query.listOrders:
      dataSource:
        type: AWS_LAMBDA
        config:
          function:
            handler: orders/handlers.listOrders
    Query.getOrder:
      dataSource:
        type: AWS_LAMBDA
        config:
          function:
            handler: orders/handlers.getOrder
    Mutation.createOrder:
      dataSource:
        type: AWS_LAMBDA
        config:
          function:
            handler: orders/handlers.createOrder

plugins:
- serverless-appsync-plugin
- serverless-esbuild
- serverless-iam-roles-per-function
- serverless-deployment-bucket
- serverless-prune-plugin

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
  Outputs:
    GraphQLApiUrl:
      Value: ${appsync:url}
    GraphQLApiKey:
      Value: ${appsync:apiKey.test}