service: appsync-merged

frameworkVersion: '3'

configValidationMode: error

provider:
  name: aws
  logRetentionInDays: 7
  region: us-east-1
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: com.reference-architecture.deploys
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  tags:
    lumigo:auto-trace: 'true'

plugins:
- serverless-deployment-bucket

resources:
  Resources:
    MergedApi:
      Type: AWS::AppSync::GraphQLApi
      Properties:
        ApiType: MERGED
        AuthenticationType: API_KEY
        MergedApiExecutionRoleArn: !Ref MergedApiExecutionRole
        Name: appsync-merged-api
    OrdersApiAssociation:
      Type: AWS::AppSync::SourceApiAssociation
      Properties:
        MergedApiIdentifier: !Ref MergedApi
        SourceApiIdentifier: arn:aws:${self:provider.region}:${AWS::AccountId}:apis/${cf:orders-source-dev.GraphQLId}
    UsersApiAssociation:
      Type: AWS::AppSync::SourceApiAssociation
      Properties:
        MergedApiIdentifier: !Ref MergedApi
        SourceApiIdentifier: arn:aws:${self:provider.region}:${AWS::AccountId}:apis/${cf:users-source-dev.GraphQLId}
    MergedApiExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - appsync.amazonaws.com
            Action: 
            - sts:AssumeRole
        RoleName: merged-api-execution-role
        Policies:
        - Effect: Allow
          Action: appsync:SourceGraphQL
          Resource:
          - arn:aws:${self:provider.region}:${AWS::AccountId}:apis/${cf:users-source-dev.GraphQLId}/*
          - arn:aws:${self:provider.region}:${AWS::AccountId}:apis/${cf:users-source-dev.GraphQLId}
          - arn:aws:${self:provider.region}:${AWS::AccountId}:apis/${cf:orders-source-dev.GraphQLId}/*
          - arn:aws:${self:provider.region}:${AWS::AccountId}:apis/${cf:orders-source-dev.GraphQLId}
