service: appsync-merged

frameworkVersion: '3'

configValidationMode: error

provider:
  name: aws
  logRetentionInDays: 7
  region: us-east-1
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: com.reference-architecture.deploys
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  tags:
    lumigo:auto-trace: 'true'

plugins:
- serverless-deployment-bucket

resources:
  Resources:
    MergedApi:
      Type: AWS::AppSync::GraphQLApi
      Properties:
        ApiType: MERGED
        AuthenticationType: API_KEY
        MergedApiExecutionRoleArn: !GetAtt MergedApiExecutionRole.Arn
        Name: appsync-merged-api
    
    # OrdersApiAssociation:
    #   Type: AWS::AppSync::SourceApiAssociation
    #   Properties:
    #     MergedApiIdentifier: !GetAtt MergedApi.ApiId
    #     SourceApiIdentifier: ${cf:orders-source-dev.GraphQLId}
    
    # UsersApiAssociation:
    #   Type: AWS::AppSync::SourceApiAssociation
    #   Properties:
    #     MergedApiIdentifier: !GetAtt MergedApi.ApiId
    #     SourceApiIdentifier: ${cf:users-source-dev.GraphQLId}
    
    MergedApiExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - appsync.amazonaws.com
            Action: 
            - sts:AssumeRole
        Path: /
        Policies:
        - PolicyName: merged-api-source-permissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: 
              - appsync:SourceGraphQL
              Resource:
              - !Sub arn:aws:appsync:${self:provider.region}:${AWS::AccountId}:apis/${cf:users-source-dev.GraphQLId}/*
              - !Sub arn:aws:appsync:${self:provider.region}:${AWS::AccountId}:apis/${cf:users-source-dev.GraphQLId}
              - !Sub arn:aws:appsync:${self:provider.region}:${AWS::AccountId}:apis/${cf:orders-source-dev.GraphQLId}/*
              - !Sub arn:aws:appsync:${self:provider.region}:${AWS::AccountId}:apis/${cf:orders-source-dev.GraphQLId}
        # - PolicyName: merged-api-schema-merge
        #   PolicyDocument:
        #     Version: '2012-10-17'
        #     Statement:
        #     - Effect: Allow
        #       Action: 
        #       - appsync:StartSchemaMerge
        #       Resource:
        #       - !Sub arn:aws:appsync:${self:provider.region}:${AWS::AccountId}:apis/${cf:appsync-merged-dev.GraphQLId}/*
        RoleName: merged-api-execution-role

    # MergedApiRolePolicies:
    #   Type: AWS::IAM::Policy
    #   Properties:
    #     PolicyName: merged-api-source-permissions
    #     PolicyDocument:
    #       Version: '2012-10-17'
    #       Statement:
    #       - Effect: Allow
    #         Action: 
    #         - appsync:SourceGraphQL
    #         Resource:
    #         - arn:aws:appsync:${self:provider.region}:${AWS::AccountId}:apis/${cf:users-source-dev.GraphQLId}/*
    #         - arn:aws:appsync:${self:provider.region}:${AWS::AccountId}:apis/${cf:users-source-dev.GraphQLId}
    #         - arn:aws:appsync:${self:provider.region}:${AWS::AccountId}:apis/${cf:orders-source-dev.GraphQLId}/*
    #         - arn:aws:appsync:${self:provider.region}:${AWS::AccountId}:apis/${cf:orders-source-dev.GraphQLId}
    #     Roles: 
    #     - !Ref MergedApiExecutionRole
